CarRental/Controllers/HistoryController.cs
using CarRental.Data;
using CarRental.Models;
using CarRental.Models.ShareDrive;
using CarRental.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace CarRental.Controllers {
    public class HistoryController : Controller {
        private readonly RentalRepository _RentalRepo;
        private readonly TicketRepository _TicketRepository;
        public HistoryController(ApplicationDbContext context) {
            _RentalRepo = new RentalRepository(context);
            _TicketRepository = new TicketRepository(context);
        }
        public async Task<IActionResult> Rental() {
            string UserID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            IEnumerable<Rental> Rentals = await _RentalRepo.GetAllFromID(UserID);
            return View(Rentals);
        }
        public async Task<IActionResult> ShareDrive() {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (string.IsNullOrEmpty(userId)) {
                Console.WriteLine("userID = null");
                // Redirect to login or handle the error appropriately
                return RedirectToAction("Login", "Account");
            }
            IEnumerable<Ticket> tickets = await _TicketRepository.GetAllTicketsByUserID(userId);
            return View(tickets);
        }


    }
}

CarRental/Controllers/VehicleController.cs
// VehicleController.cs
using CarRental.Data;
using CarRental.Models;
using CarRental.Service;
using CarRental.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Collections.Generic;
using System.Net;
using System.Security.Claims;
using static System.Runtime.InteropServices.JavaScript.JSType;
using CarRental.Services;
using Microsoft.AspNetCore.Identity;

namespace CarRental.Controllers
{
    public class VehicleController : Controller {
        private VehicleService vehicleService;
        private RentalService rentalService;
        private readonly UserManager<ApplicationUser> _userManager;

        public VehicleController(
            ApplicationDbContext context,
            IWebHostEnvironment webHostEnvironment,
            NotificationService notificationService,
            UserManager<ApplicationUser> userManager)
        {
            vehicleService = new VehicleService(context, webHostEnvironment);
            rentalService = new RentalService(context, webHostEnvironment, notificationService, userManager);
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(string searchString)
        {
            IEnumerable<Vehicle> vehicles = await vehicleService.getAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                vehicles = vehicles.Where(v => v.Brand.Contains(searchString, StringComparison.OrdinalIgnoreCase));
            }

            return View(vehicles);
        }
        public async Task<IActionResult> AllVehiclePartial(bool isForDetails, int currentId, string searchString)
        {
            IEnumerable<Vehicle> vehicles = await vehicleService.getAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                vehicles = vehicles.Where(v => v.Brand.Contains(searchString, StringComparison.OrdinalIgnoreCase));
            }

            ViewData["IsForDetails"] = isForDetails;
            ViewData["CurrentId"] = currentId;

            return PartialView("_DisplayVehicles", vehicles);
        }

        [Authorize]
		[HttpGet]
		public async Task<IActionResult> CreateEdit(int id) {
			if (id == 0) {
				// Create
				ViewBag.Operation = "Upload";
				return View(new Vehicle());
			} else {
				// Edit
				ViewBag.Operation = "Edit";
                var queryOption = new QueryOption<Vehicle> {
                    Includes = "Gallery"
                };
                Vehicle vehicle = await vehicleService.GetByIdAsync(id, queryOption);
				return View(vehicle);
			}
		}

		[HttpPost]
		public async Task<IActionResult> CreateEdit(Vehicle vehicle) {
			vehicle.OwnerId = User.FindFirstValue(ClaimTypes.NameIdentifier);

			if (vehicle.RentalVehicleID == 0) {
				if (ModelState.IsValid) {
					//add
					vehicleService.AddVehicleAsync(vehicle);
					return RedirectToAction("Index", "ApplicationUser");
				}
			} else {
				//edit
				// Skip the validation for IFormFile properties (ThumbnailImage, ImageGallery)
				if (vehicle.ThumbnailImage == null) {
					ModelState.Remove("ThumbnailImage"); // Remove validation for ThumbnailImage
				}
				if (vehicle.ImageGallery == null || vehicle.ImageGallery.Count == 0) {
					ModelState.Remove("ImageGallery"); // Remove validation for ImageGallery
				}
				if (ModelState.IsValid) {
					var result = await vehicleService.EditVehicleAsync(vehicle);
					if (!result.Success) {
						ModelState.AddModelError("", result.Errors.FirstOrDefault());
						return View(); // Return an error view
					}

					return RedirectToAction("Index", "ApplicationUser");
				}
				/*if (!ModelState.IsValid) {
					foreach (var key in ModelState.Keys) {
						var errors = ModelState[key].Errors;
						foreach (var error in errors) {
							Console.WriteLine($"Key: {key}, Error: {error.ErrorMessage}");
						}
					}
				}*/
			}
			return View(vehicle);
		}

		[HttpPost]
		public async Task<IActionResult> Delete(int id) {
			var result = await vehicleService.DeleteVehicleAsync(id);
			if (!result.Success) {
				foreach (var error in result.Errors) {
					ModelState.AddModelError("", error); // Add error messages to ModelState
				}
				return RedirectToAction("Index", "ApplicationUser");
			}
			return RedirectToAction("Index", "ApplicationUser");
		}

		[HttpGet]
		public async Task<IActionResult> Details(int id) {
			var queryOption = new QueryOption<Vehicle> {
				Includes = "Gallery, Owner"
			};
			Vehicle vehicle = await vehicleService.GetByIdAsync(id, queryOption);
			return View(vehicle);
		}

		[HttpGet]
		public async Task<IActionResult> Compare(int currentId, int id) {
			var queryOption = new QueryOption<Vehicle> {
				Includes = "Gallery"
			};

			Vehicle currentVehicle = await vehicleService.GetByIdAsync(currentId, queryOption);
			Vehicle compareVehicle = await vehicleService.GetByIdAsync(id, queryOption);

			List<Vehicle> vehicles = new List<Vehicle>();
			vehicles.Add(currentVehicle);
			vehicles.Add(compareVehicle);

			return View(vehicles);
		}

		[Authorize]
		[HttpGet]
		public async Task<IActionResult> Rent(int id) {
			var queryOption = new QueryOption<Vehicle> {
				Includes = "Gallery, Owner"
			};
			Rental rent = new Rental();
			rent.UserID = User.FindFirstValue(ClaimTypes.NameIdentifier);
			rent.RentalVehicleID = id;
			return View(rent);
		}

		[HttpGet]
		[Route("api/rentalvehicles/{rentalVehicleId}")]
		public async Task<IActionResult> GetRentalVehicleFee(int rentalVehicleId) {
			// Example: Fetch data from repositories or services
			var queryOption = new QueryOption<Vehicle> {
				Includes = "Gallery, Owner"
			};
			Vehicle vehicleData = await vehicleService.GetByIdAsync(rentalVehicleId, queryOption);

			if (vehicleData == null) {
				return NotFound("Rental Vehicle data not found.");
			}

			return Json(new {
				FeePerDay = vehicleData.RentalFeePerDay,
				OwnerName = vehicleData.Owner.UserName,
				OwnerEmail = vehicleData.Owner.Email,
				OwnerPhone = vehicleData.Owner.PhoneNumber,
			});
		}

		[HttpPost]
		public async Task<IActionResult> Rent(Rental rental) {
			rental.UserID = User.FindFirstValue(ClaimTypes.NameIdentifier);
			if (ModelState.IsValid) {
				var result = await rentalService.rent(rental);

				if (!result.Success) {
					foreach (var error in result.Errors) {
						ModelState.AddModelError("", error);
					}
					return View(rental);
				}
                TempData["SuccessMessage"] = "Car rental was successful!";
                return RedirectToAction("Index");
			}
			return View(rental);
		}

		/*[HttpGet]
		public async Task<IActionResult> Search(string keyword)
		{
			IEnumerable<Vehicle> vehicles = await vehicleService.searchVehicles(keyword);
			if (!vehicles.Any())
			{
				return NotFound();

			}

			ViewData["IsForDetails"] = false;
			return PartialView("_DisplayVehicles", vehicles);
		}*/
	}
}

CarRental/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarRental</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarRental.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
          crossorigin="" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css"/>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
            integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
            crossorigin=""></script>
    
</head>
<body>
    <header class="fixed-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="#" id="toggleSidebar">CAPY</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="Index">Rent</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShareDrive" asp-action="PassengerRide">Book</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>

                <!-- Sidebar -->
                <div id="sidebar">
                    <span class="close-btn" id="closeSidebar">&times;</span>
                    <ul>
                        <li><a href="/"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
                        <li><a class="" asp-controller="ApplicationUser" asp-action="Index"> <i class="fa-solid fa-car-side"></i> My Car</a></li>
                        @if (!User.IsInRole("Driver")) {
                            <li><a class="" asp-controller="Driver" asp-action="RegisterDriver"><i class="fas fa-car"></i> Register as driver</a></li>
                        } else {
                            @* meaning that this user already a driver *@
                            <li><a class="" asp-controller="ShareDrive" asp-action="DriverOpen"><i class="fas fa-car"></i> Open share drive</a></li>
                            <li><a class="" asp-controller="ShareDrive" asp-action="YourDriverRideList"><i class="fas fa-car"></i> Your rides</a></li>
                        }
                        @if (User.IsInRole("Admin")) {
                            <li><a class="" asp-controller="Admin" asp-action="Approve"><i class="fas fa-person"></i> Approval</a></li>
                        }
                        <li class="dropdown">
                            <a href="javascript:void(0)" class="dropdown-btn">
                                <i class="fas fa-history"></i> History <i class="fas fa-chevron-down"></i>
                            </a>
                            <ul class="dropdown-content">
                                <li><a asp-controller="History" asp-action="Rental">Rental</a></li>
                                <li><a asp-controller="History" asp-action="ShareDrive">Booking</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container content">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CarRental - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const sidebar = document.getElementById('sidebar');
            const toggleSidebar = document.getElementById('toggleSidebar');
            const closeSidebar = document.getElementById('closeSidebar');

            toggleSidebar.addEventListener('click', function () {
                sidebar.classList.add('active');
            });

            closeSidebar.addEventListener('click', function () {
                sidebar.classList.remove('active');
            });

            document.addEventListener('click', function (e) {
                if (!sidebar.contains(e.target) && !toggleSidebar.contains(e.target)) {
                    sidebar.classList.remove('active');
                }
            });
        });
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>


</html>